const state = {
  config: null,
  snapshotPayload: null,
  activeTab: "movement",
  loading: false,
  data: null,
  aggregatedManualRange: null,
  googleAuth: {
    clientId: "",
    scopes: "",
    tokenClient: null,
    accessToken: "",
    configured: false,
    initialized: false,
    initializing: false,
    readyError: ""
  },
  manualServer: {
    enabled: true,
    fallbackVisible: false,
    activeRoute: "/api/manual-finance",
    cache: new Map(),
    inFlight: new Map()
  },
  dashboardRequests: {
    debounceTimer: null,
    inFlight: new Map(),
    lastLoadedAt: new Map()
  },
  manualFinance: {
    loading: false,
    data: null,
    periods: [],
    dirty: false,
    status: "",
    error: false
  },
  expenseAccounting: {
    activeSubtab: "list",
    expensePieMode: "direction",
    resultTab: "spent",
    operationsFilters: {
      source: "all",
      operation: "all",
      accountChannel: "all",
      fromChannel: "all",
      toChannel: "all"
    },
    editingSheetRowNumber: 0,
    operationDraft: null,
    loading: false,
    paypalLoading: false,
    paypalSummary: null,
    paypalManualBalanceRequired: false,
    paypalManualBalanceSaving: false,
    paypalDerivedBalanceLoading: false,
    paypalManualBalance: {
      date: "",
      USD: "",
      EUR: "",
      CAD: "",
      comment: ""
    },
    payoneerLoading: false,
    payoneerSummary: null,
    wiseLoading: false,
    wiseSummary: null,
    wiseBalanceSnapshotKeys: new Set(),
    yoomoneyLoading: false,
    yoomoneySummary: null,
    statementImportLoading: false,
    monobankLoading: false,
    monobankSummary: null,
    monobankConnectOpen: false,
    monobankValidating: false,
    monobankToken: "",
    monobankAccounts: [],
    monobankSelectedAccountId: "",
    monobankValidationMessage: "",
    monobankValidationError: false,
    monobankClientName: "",
    monobankMode: "",
    privatBankLoading: false,
    privat24ImportLoading: false,
    privat24Preview: null,
    privatBankSummary: null,
    tdBankLoading: false,
    tdImportStep: "ready",
    tdImportClipboardRetry: false,
    tdBankSummary: null,
    entries: [],
    warnings: [],
    status: "",
    error: false
  },
  manualTransfers: {
    loading: false,
    data: null,
    dirty: false,
    status: "",
    error: false
  },
  manualOrders: {
    loading: false,
    data: null,
    dirty: false,
    status: "",
    error: false,
    textDraft: ""
  },
  analyticsFact: {
    periodStart: "",
    periodEnd: "",
    moneyTitle: "",
    moneyHeaders: [],
    moneyRows: []
  }
};

const elements = {
  startDate: document.getElementById("startDate"),
  endDate: document.getElementById("endDate"),
  status: document.getElementById("status"),
  endpointLabel: document.getElementById("endpointLabel"),
  manualEndpointLabel: document.getElementById("manualEndpointLabel"),
  metricPeriod: document.getElementById("metricPeriod"),
  metricOrders: document.getElementById("metricOrders"),
  metricBalances: document.getElementById("metricBalances"),
  metricTransfers: document.getElementById("metricTransfers"),
  metricPersonalOrdersAfterDiscount: document.getElementById("metricPersonalOrdersAfterDiscount"),
  metricMyServices: document.getElementById("metricMyServices"),
  metricProfit: document.getElementById("metricProfit"),
  metricMyCosts: document.getElementById("metricMyCosts"),
  metricPersonalOrdersAfterDiscount: document.getElementById("metricPersonalOrdersAfterDiscount"),
  tabs: document.getElementById("tabs"),
  tabPanels: document.getElementById("tabPanels"),
  todayButton: document.getElementById("todayButton"),
  weekButton: document.getElementById("weekButton"),
  calculateButton: document.getElementById("calculateButton"),
  connectGoogleButton: document.getElementById("connectGoogleButton"),
  disconnectGoogleButton: document.getElementById("disconnectGoogleButton")
};
